### ISSUE TITLE
How can we obtain pre-assembled units?

### ISSUE THREAD

**Issue by ElDominio** [corygrant/dingoPDM#1]
I know a large group of software guys who might be interested in acquiring a pre-assembled unit to play around with code. Where can I point them to? Is there a Slack channel for this project?

**Comment by corygrant** [comment]
Currently the only units are the ones I've built, but if you'd like we can talk about building some more. 
There's no Slack channel yet, but I could create one if you like?

**Comment by bryanbendall** [comment]
I would be interested in it as well.

**Comment by corygrant** [comment]
I'm going to build a batch of V4 boards soon, would you be interested in buying an assembled unit?

**Comment by bryanbendall** [comment]
Yes an assembled one would be good. I would like to try it out with the software I'm working on. I made some of my own boards but they need to be updated. Hard to find parts right now. Any idea on the cost of them yet?

**Comment by corygrant** [comment]
It's probably not cost effective (or timely) for me to do assembly by hand. 
Purchasing parts from Digikey/Mouser the BOM cost is around $150 right now, plus maybe $4 for a PCB. 
But, it takes me hours to assemble one of these by hand. 

Maybe the next step should be getting this setup for PCBA through JLC or similar.

**Comment by JZXPacky** [comment]
Any chance you've got this setup for JLC etc yet? I'm very interested in building one of these units and incorporating into my car with a Haltech Elite 2500.

**Comment by corygrant** [comment]
@JZXPacky no not yet. I've done a little testing when I've been able to find the time, but not to a point that I would want to order more assembled boards. 
Feel free to use the Kicad files and BOMs to set it up though!

**Comment by corygrant** [comment]
Just finished a batch of pre built PDMs. 
Working on getting the online shop set up, but PayPal also works

**Comment by ZHoob2004** [comment]
Based on the new pictures in the repo, it looks like you have some units in hand. I could be interested in buying one, but I'm not sure how to contact you outside of github issues.

**Comment by corygrant** [comment]
@ZHoob2004 I just opened the store site up, first shipments from the store going out Monday 5/13. 
https://dingo-electronics.square.site/
